### ISSUE TITLE
Revisit the hierarchy of configuration properties and make them consistent

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1278]
Recently we had a few issues:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/326
https://github.com/spring-cloud/spring-cloud-stream/pull/1276
etc. . .
They are all in one way or the other tied to configuration properties hierarchies that begin with boot and transcend to SCSt and then binders.
There seem to be a bit of inconsistency, so a review is in order

**Comment by 2speed** [comment]
Greetings, I ran into an issue similar to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/326 using Spring Boot with the Kafka streams binder when attempting to bridge a stream from an external Kafka cluster. Here is a snippet from my `application.yml` file:

```
spring.cloud.stream:
  bindings:
    input:
      destination: ...
      binder: kBind1
  binders:
    kBind1:
      type: kstream
      environment:
        spring.cloud.stream.kafka.streams.binder:
          brokers: ...
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
...
```

Running the application results in the following error:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field kafkaProperties in org.springframework.cloud.stream.binder.kafka.streams.KStreamBinderConfiguration required a bean of type 'org.springframework.boot.autoconfigure.kafka.KafkaProperties' that could not be found.
```

**Comment by olegz** [comment]
@2speed could you please try Elmhurs.SR1 that was released [last week](https://spring.io/blog/2018/07/12/spring-cloud-stream-elmhurst-sr1-released) . I believe we've seen similar issue and it have been fixed in that release

**Comment by 2speed** [comment]
@olegz Switched to `Elmhurst.SR1` and I still get the same error.

Code Snippet:
```java
@SpringBootApplication()
public class StreamSourceApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(StreamSourceApplication.class, args);
    }
    
    @EnableBinding(StreamSourceProcessor.class)
    public static class StreamSourceConfiguration {
        
        @StreamListener
        public void handle(@Input("inbound") KStream<Object, Map<String, Object>> stream) {
            stream.foreach((k, v) -> {
                System.out.println("\n" + k + ":\n" + v + "\n");
            });
        }
    }
    
    interface StreamSourceProcessor {
        @Input("inbound")
        KStream<?, ?> sdpInbound();
    }
}
```
Gradle Build Snippet:
```gradle
ext {
	springCloudVersion = 'Elmhurst.SR1'
}

dependencies {
    testCompile 'org.springframework.boot:spring-boot-starter-test'
    testCompile 'org.springframework.cloud:spring-cloud-stream-test-support'

    ...

    // Spring : SCS
    compile 'org.springframework.cloud:spring-cloud-stream'
    compile 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-stream-dependencies:${springCloudVersion}"
	}
}
```

**Comment by olegz** [comment]
Can you try one last thing and change your code yo look like this
```
@SpringBootApplication()
@EnableBinding(StreamSourceProcessor.class)
public class StreamSourceApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(StreamSourceApplication.class, args);
    }
    
    @StreamListener
    public void handle(@Input("inbound") KStream<Object, Map<String, Object>> stream) {
       stream.foreach((k, v) -> {
           System.out.println("\n" + k + ":\n" + v + "\n");
       });
    }
    
    interface StreamSourceProcessor {
        @Input("inbound")
        KStream<?, ?> sdpInbound();
    }
}
```

**Comment by 2speed** [comment]
Unfortunately that did not work either. Results in the same error:

Code:
```java
package com.esm.stream;

import java.util.Map;

import org.apache.kafka.streams.kstream.KStream;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.annotation.EnableBinding;
import org.springframework.cloud.stream.annotation.Input;
import org.springframework.cloud.stream.annotation.StreamListener;

@SpringBootApplication()
@EnableBinding(com.esm.stream.StreamSourceApplication.StreamSourceProcessor.class)
public class StreamSourceApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(StreamSourceApplication.class, args);
    }
    
    @StreamListener
    public void handle(@Input("inbound") KStream<Object, Map<String, Object>> stream) {
       stream.foreach((k, v) -> {
           System.out.println("\n" + k + ":\n" + v + "\n");
       });
    }
    
    interface StreamSourceProcessor {
        @Input("inbound")
        KStream<?, ?> sdpInbound();
    }
}
```

**Comment by sobychacko** [comment]
@2speed Could you create an issue in the kafka binder repository and provide the minimal configuration for reproducing it? We will take a look there.

**Comment by 2speed** [comment]
Done: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/411

**Comment by olegz** [comment]
This may actually have been fixed already with [this](https://github.com/spring-cloud/spring-cloud-stream/commit/460ba9cecb27bc4b2d6e7c23a5fed0177119d68c)

**Comment by olegz** [comment]
I am closing it based on the mentioned fix in Kafka as well as https://github.com/spring-cloud/spring-cloud-stream/commit/460ba9cecb27bc4b2d6e7c23a5fed0177119d68c

Feel free to reopen it with fresh details if you still see an issue
