### ISSUE TITLE
Kafka-stream not serialize value as long

### ISSUE THREAD

**Issue by MadeInChina** [spring-cloud/spring-cloud-stream#1345]
Kafka-stream not serialize value as long
I had code to read msg from kafka and send  to a new topic(out-put-topic).

```
@StreamListener("input")
  @SendTo("output")
  public KStream<String, Long> process(KStream<String, Event> input) {

    return input
        .map(((key, value) -> KeyValue.pair(LocalDate.now().toString(), 1L)))
        .filter(
            (key, msg) -> {
              System.out.println("Got a message! key = {}, value = {}" + key + "  " + msg);
              return true;
            })
        .groupBy(((key, value) -> key), Serialized.with(Serdes.String(), Serdes.Long()))
        .reduce((e1, e2) -> e1 + e2)
        .toStream();
  }
```
application.yml
```
spring.cloud.stream.bindings.output:
  destination: out-put-topic
  producer:
    useNativeEncoding: true
    keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
    valueSerde: org.apache.kafka.common.serialization.Serdes$LongSerde
    headerMode: raw
```
in another project i had code to read msg from out-put-topic
```
@KafkaListener(topics = "${spring.kafka.topic}")
  public void receive(ConsumerRecord<String, String> record) {
    System.out.println("key:" + record.key() + " value:" + record.value());
     }
```
application.yml
```
spring:
  kafka:
    bootstrap-servers: broker1:9092, broker2:9092, broker3:9092
    topic: out-put-topic
    consumer:
      group-id: myGroup
      client-id: clientid
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: out-put-topic
```
value-deserializer must using org.apache.kafka.common.serialization.StringDeserializer

for value-deserializer: org.apache.kafka.common.serialization.LongDeserializer not working

```
Cause
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition out-put-topic-0 at offset 1. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: Size of data received by LongDeserializer is not 8

2018-04-04 10:09:25.249 ERROR 1 --- [ntainer#0-0-C-1] essageListenerContainer$ListenerConsumer : Container exception

org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition out-put-topic-0 at offset 1. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: Size of data received by LongDeserializer is not 8
```

**Comment by MadeInChina** [comment]
fixed by
```
spring.cloud.stream.bindings.output:
  destination: out-put-topic
  producer:
    useNativeEncoding: true
spring.cloud.stream.kafka.streams.bindings.output.producer:
    keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
    valueSerde: org.apache.kafka.common.serialization.Serdes$LongSerde

```

**Comment by mammenj** [comment]
I am still getting the same issue with  Hoxton.RELEASE with Java 11

**Comment by olegz** [comment]
@mammenj Please do not comment on closed issues especially with questions. For questions we use [Stack Overflow channel](https://stackoverflow.com/tags/spring-cloud-stream).
