### ISSUE TITLE
Not able to bind to multiple binders for Spring-cloud-stream kafka

### ISSUE THREAD

**Issue by pathiksheth14** [spring-cloud/spring-cloud-stream#1404]
I am trying to bind two kafka broker and send and consume messages from both. But while initializing only one broker gets connected, the first one. Second one always fails.

Further debugging shows that for the second broker fails in Fetcher.java:

client.poll(future, remaining); returns org.apache.kafka.common.errors.DisconnectException. 

When I run both this broker individually both works fine.

I am using 1.5.8.RELEASE of spring boot and Dalston.SR4 for spring cloud.

application.yml is attached.
[application.txt](https://github.com/spring-cloud/spring-cloud-stream/files/2152871/application.txt)

This is really important for me. Any input will be of great help.

**Comment by olegz** [comment]
Could you please attach stack trace, so we can see the actual error you're having?

**Comment by pathiksheth14** [comment]
Hi Oleg,

    Thank you for quick response.

    I will be able to share logs tomorrow as I return to work.

    As per my understanding it will take more than 10 mins to throw error as wait time is around 60000 ms and there are 10 attempts and further wait while doing client.send(future, something);

    In mean time can you have a look at yml and see if something wrong there.Some configuration that is not proprely defined.

    I also want to check whether this is expected scenario and not a limitation for Dalston.SR4.

Thanks,
Pathiik

**Comment by pathiksheth14** [comment]
Error after 60000 ms.
```
2018-07-02 16:32:07.467 ERROR 13196 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is org.springframework.cloud.stream.binder.BinderException: Cannot initialize binder:
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at com.bnym.fnv.QueryServiceApplication.main(QueryServiceApplication.java:30) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.8.RELEASE.jar:1.5.8.RELEASE]
Caused by: org.springframework.cloud.stream.binder.BinderException: Cannot initialize binder:
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:271) ~[spring-cloud-stream-binder-kafka-core-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:149) ~[spring-cloud-stream-binder-kafka-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:88) ~[spring-cloud-stream-binder-kafka-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:112) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:57) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:152) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:124) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:238) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	... 19 common frames omitted
Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

Disconnected from the target VM, address: '127.0.0.1:61512', transport: 'socket'

Process finished with exit code 0
```

**Comment by olegz** [comment]
This seems to be pointing to a miss-configured Kafka producer/consumer. If you google around there are plenty of references to `org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.` You should also the kafka service logs which may contain more details.
Also, in your configuration you pointing to` kafka1` and `kafka2` binders, but configure `cnj` and `tpc`. . . . Not sure what you're trying to do there.

Please consider following [this section](https://docs.spring.io/spring-cloud-stream/docs/Ditmars.SR4/reference/htmlsingle/#multiple-binders) for multi-binder configurations

**Comment by sobychacko** [comment]
@pathiksheth14 here is a [sample application](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/multibinder-samples/multibinder-two-kafka-clusters) that uses two kafka clusters and bind to both of them. You might want to compare your application with this.

**Comment by pathiksheth14** [comment]
@olegz  both this binder works fine if I remove one and run other one individually. That means binders are pointing to right kafka cluster/brokers.

cnj and tpc are our internal representation. I didn't wanted to share it so renamed it to tpc and cnj.

**Comment by olegz** [comment]
All I am saying is that your configuration appears incorrect, so there is nothing for us to go by other then provide you with a working example (as Soby did), so please follow the example application while modifying configuration with values representing your environment and let us know

**Comment by pathiksheth14** [comment]
@sobychacko I have configured my project by using exact same example.

But when I use your project and configure yaml file using our cluster and jaas configurations, it gives login error. I think springboot 2.0.0,kafka 2.0.0.Release and Finchley.Release are not reading jaas config from my yaml file. Is there any change in jaas configuration for latest versions.

**Comment by pathiksheth14** [comment]
@olegz 

Thank you for quick response. Here is my config file. 
```
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      enabled: false
    stream:
      kafka:
        binder:
          jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
          configuration:
            "[security.protocol]": SASL_PLAINTEXT
            "[sasl.mechanism]": PLAIN
      bindings:
        sampleQueueA:
          destination: FNV_HOLDINGS
          binder: tpc
          group: FNV_HOLDINGS
        sampleQueueB:
          destination: FNV_SECURITIES
          binder: cnj
          group: FNV_SECURITIES
      binders:
        tpc:
         type: kafka
         defaultCandidate: false
         inheritEnvironment: false
         environment:
           spring:
             cloud:
               stream:
                kafka:
                  binder:
                    brokers: ${broker1}
                    autoCreateTopics: false
                    jaas:
                      options:
                        username: ${username1}
                        password: ${password1}
        cnj:
         type: kafka
         defaultCandidate: false
         inheritEnvironment: false

         environment:
           spring:
             cloud:
               stream:
                kafka:
                  binder:
                    brokers: ${broker2}
                    autoCreateTopics: false
                    jaas:
                      options:
                        username: ${username2}
                        password: ${password2}

```
If I use tpc binder for both topics it works fine. If use cnj binder for both topics it works fine. It give problem when I use tpc for one cnj for one.

Our topic names are same in both this binder. Can this be an issue(though from my debugging I think that should not be an issue)?

**Comment by sobychacko** [comment]
@pathiksheth14 Any chance you can create a small application in which you re-create this issue and share with us? That way, we can run it on our end and debug more effectively.

**Comment by pathiksheth14** [comment]
@sobychacko , Sure I will do that asap.

Thank you

**Comment by olegz** [comment]
@pathiksheth14 were you able to create a sample app that reproduces the issue that we can look at? Also, have you tried a sample provided by Soby?

**Comment by olegz** [comment]
Closing it as stale. No response from user and no way to reproduce

**Comment by pathiksheth14** [comment]
Hi @olegz/ @sobychacko ,

Sorry for the delayed response. We had deadlines and we went ahead with single broker at the moment. I was very much occupied with it and that's why could not revert back. 

I am working with this [sample application](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/multibinder-samples/multibinder-two-kafka-clusters) to come up with solution for our app.

Please let me know whether I should raise another ticket or is there any other forum where I can raise it.

I have used exactly same code by providing below yml. Right now I am facing issue while connecting to kafka servers because its not reading jaas parameters. I have debugged code and came up with below yml such that in DefaultBinderFactory while calling below line

```
ConfigurableApplicationContext binderProducingContext = springApplicationBuilder.run((String[])args.toArray(new String[args.size()]));
```
it has below args
```
0 = "--spring.cloud.stream.kafka.binder.jaas.options.username=abcdxyz"
1 = "--spring.cloud.stream.kafka.binder.jaas.loginModule=org.apache.kafka.common.security.plain.PlainLoginModule"
2 = "--spring.cloud.stream.kafka.binder.jaas.options.password=abcdxyz"
3 = "--spring.cloud.stream.kafka.binder.brokers=kafkainstance1:9092"
4 = "--spring.jmx.default-domain=nullbinder.kafka1"
```

I can see same args in applicationArguments of SpringApplication.java but in AppConfigurationEntry this values are not reflecting and this is what I see:

com.sun.security.auth.module.Krb5LoginModule

Can you review this yml? I tried a lot but could not resolve this.

```
spring:
  cloud:
    stream.kafka.binder.configuration.[security.protocol]: SASL_PLAINTEXT
    stream.kafka.binder.configuration.[sasl.mechanism]: PLAIN
    stream.kafka.binder.jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
    stream:
      bindings:
        input:
          destination: F_H_LOCAL
          binder: kafka1
          group: testGroup
        output:
          destination: F_S_LOCAL
          binder: kafka2
        #Test sink binding (used for testing)
        output1:
          destination: F_H_LOCAL
          binder: kafka1
        #Test sink binding (used for testing)
        input1:
          destination: F_S_LOCAL
          binder: kafka2
      binders:
        kafka1:
         type: kafka
         environment:
           spring:
             cloud:
               stream:
                kafka:
                  binder.brokers: kafkainstance1:9092
                  binder.jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
                  binder.jaas.options.username: abcdxyz
                  binder.jaas.options.password: abcdxyz
        kafka2:
         type: kafka
         environment:
           spring:
             cloud:
               stream:
                 kafka:
                   binder:
                     brokers: kafkainstance2:9092
                     jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
                     jaas.options.username: abcdxyz
                     jaas.options.password: abcdxyz

```

**Comment by olegz** [comment]
@pathiksheth14 We've seen some issues recently with multi-binder support and addressed them prior to releasing 2.0.1 (service release). While @sobychacko will take a look a bit deeper, would you mind running a quick test against the 2.0.1? For details please see https://spring.io/blog/2018/07/12/spring-cloud-stream-elmhurst-sr1-released

**Comment by pathiksheth14** [comment]
I tried with 2.0.1.RELEASE version for spring-cloud-stream-binder-kafka and spring-cloud-stream-binder-kafka-core and spring-cloud-stream version of Elmhurst.SR1 but faced the same issue.

**Comment by pathiksheth14** [comment]
Hi @olegz / @sobychacko , 

     Did you get chance to look into this?

**Comment by sobychacko** [comment]
@pathiksheth14 We will look at this issue soon and get back to you with any updates.

**Comment by sobychacko** [comment]
@pathiksheth14 I am going to close this issue and move this over to the kafka binder repository. This turned out to be a bug on the binder side. We will fix it and backport to 2.0.x.

**Comment by sobychacko** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#419

**Comment by sobychacko** [comment]
@pathiksheth14 I added some comments on the issue mentioned above in the Kafka binder. Not sure if you saw them. Would you mind checking those out?

**Comment by pathiksheth14** [comment]
@sobychacko Thanks a lot for fixing the issue quickly. I might not able to try this fix before Wednesday as I won't have access to my system for next two days. But I will update you as soon as possible.

Just to confirm, this issue is now available in 2.1.0.M2 and I will have to use this version of spring-cloud-stream-binder-kafka.  Correct me here, if that's not the case.

**Comment by pathiksheth14** [comment]
@sobychacko ,  when this version will be released?

**Comment by pathiksheth14** [comment]
Hi @sobychacko , when this fix will be released. We are going into production next month and this one fix is very critical for us. 

I am not sure if I should check this elsewhere. If that't the case, can you please guide me where I can track it.

**Comment by ignesious** [comment]
@pathiksheth14 Are you guys able to solve this issue ?. If so please let us know the application.properties file.

**Comment by landaumd** [comment]
Hi all - any word on this issue? We are having the same problem - only the first binder's configurations are picked up. Please let me know if there is a specific version where this feature is working?

**Comment by olegz** [comment]
What do you mean `any word on this issue?`?, It's been addressed in M4 and the issue is closed. . . Please clarify

**Comment by TuvaevAndrey** [comment]
Hi everyone. Still have issue on spring-cloud-stream-binder-kafka:2.1.4.RELEASE and spring-kafka:2.2.8.RELEASE with multiple binders with different jaas configuration.
As I see the issue is connected with _org.springframework.kafka.security.jaas.KafkaJaasLoginModuleInitializer.InternalConfiguration_  
 class and _org.springframework.kafka.security.jaas.KafkaJaasLoginModuleInitializer#afterSingletonsInstantiated_ method which initializes it.

Method is called just for the first binder so _javax.security.auth.login.Configuration_ contains only first binder's props.

**Comment by abhinaba-chakraborty-by** [comment]
Facing same issue with `'org.springframework.cloud:spring-cloud-stream-binder-kafka:3.0.9.RELEASE'`. @TuvaevAndrey @landaumd @pathiksheth14 Did you guys find any workaround with this?

**Comment by bmlikota** [comment]
This works for me

`cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          brokers:
            - my-release-kafka.kafka:9092
      bindings:
        cbc-message-id-consumer:
          binder: kafka-1
          destination: cbc-message-id-topic
          content-type: text/plain
          group: cbc-message-id-group # only one consumer will consume one message
        cbe-outbound-message-producer:
          binder: rabbit-1
          destination: cbe-outbound-message-exchange
          content-type: text/plain
      binders:
        kafka-1:
          type: kafka
        rabbit-1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: my-release-rabbitmq.rabbitmq
                port: 5672
                username: ertert
                password: werwetew`

Suppose that it would work with multiple kafka brokers

**Comment by velovint** [comment]
@abhinaba-chakraborty-by see updated multi binder sample at https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/multi-binder-samples/kafka-multi-binder-jaas

Thanks @sobychacko for that!
