### ISSUE TITLE
Binding not found anymore in 3.x ?

### ISSUE THREAD

**Issue by vincent-fuchs** [spring-cloud/spring-cloud-stream#1825]
Hi,

I just upgraded my project to Spring Boot 2.2 and I wanted to also upgrade Spring Cloud from Greenwich.SR1 to Hoxton.M3 as recommended. However, with the upgrade to Hoxton.M3, that brings Spring Cloud Stream 3.0.0.M4 , my build fails with a test failure :

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'push-on-default-branch' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:805)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1278)
```

I have created an issue on my project : https://github.com/societe-generale/ci-droid-tasks-consumer/issues/70 

Is there a _not-documented-yet_ change that would explain this ? I see on https://spring.io/blog/2019/08/19/announcing-spring-cloud-stream-horsham-m3-3-0-0-m3 that @StreamListener and @EnableBinding may be deprecated in the future, but I understand there should be no impact for now.

Please note my test works fine with Spring Cloud Greenwich.SR1 - the **only** change that I make to get the failure is the upgrade to Hoxton.M3

**Comment by olegz** [comment]
The `EnableBinding` and `StreamListener` are not deprecated and as of now there are no plans to do so. We simply recommend for users to switch to functional approach if they can. That said, i looked at your project and there are many variables, yet non of them (based on the stack trace) points to spring-cloud-stream issue. Keep in mind that Hoxton.M3 is the BOM for [spring-cloud](https://github.com/spring-cloud) which consists of  many projects and while there may be some issues with upgrade, so far I don't see any evidence of a stream issue. You can easily verify that by creating a new simple stream project based on Hoxton.M3

**Comment by olegz** [comment]
@vincent-fuchs I tried to look at your project(s) and there is too much going on to treat it as a way to reproduce the issue. Can you please narrow it down to only what's required. Also, please include full stack trace since the above doesn't provide us with any any information that could be used to diagnose the issue.

**Comment by olegz** [comment]
Also, we've just released Horsham.RELEASE which is based on Hoxton.RELEASE which are boot 2.2.x compatible

**Comment by vincent-fuchs** [comment]
thanks for the update. Unfortunately, it still doesn't work. I guess I need to spend some time investigating !

**Comment by sabbyanandan** [comment]
Closing this due to no activity.

**Comment by vincent-fuchs** [comment]
for what it's worth : I've upgraded to Spring Cloud Hoxton, and moved to the recommended approach, ie get rid of @EnableBinding and use functions instead. For some reason, it still wasn't working with @EnableBinding, even it should have.. 

code changes I made on my project are available here : https://github.com/societe-generale/ci-droid-tasks-consumer/pull/71
