### ISSUE TITLE
Spring Cloud Stream Kafka 4.0.0 Tombstone: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "result" is null 

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-stream#2614]
When upgrading to Spring Cloud Stream Kafka 4.0.0 tombstone messages no longer work and result in a 

```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "result" is null
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.doPostProcessResult(CloudEventsFunctionInvocationHelper.java:138)
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:114)
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:48)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:175)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:143)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:139)
```

I have distilled the problem down into the following test which works fine in previous releases but breaks in Spring Cloud Stream Kafka 4.0.0  

```
@SpringBootApplication
@SpringBootTest
@TestPropertySource(properties = {
    "spring.cloud.stream.bindings.test-out-0.destination=test"
    ,"spring.cloud.stream.kafka.bindings.test-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer"
    ,"spring.cloud.stream.kafka.bindings.test-out-0.producer.configuration.value.serializer=org.springframework.kafka.support.serializer.JsonSerializer"
      
})
public class KafkaNullTest {
  
  @Autowired
  private StreamBridge streamBridge;

  @Test
  void testName() throws Exception {
    String id = UUID.randomUUID().toString();
    Message<KafkaNull> kafkaEvent = MessageBuilder
            .withPayload(KafkaNull.INSTANCE)
            .setHeader(KafkaHeaders.KEY, id).build();
    streamBridge.send("test-out-0", kafkaEvent);
  }
  
}
```

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.1</version>
		<!--version>2.7.5</version-->		
	</parent>
	<groupId>uk.co.ii</groupId>
	<artifactId>spring-cloud-fucntion-zipkin</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>spring-cloud-fucntion-zipkin</name>
	<description>Demo project for Spring Boot</description>
	<properties>
	    <sonar.projectKey>${project.artifactId}</sonar.projectKey>
		<java.version>17</java.version>
		<spring-cloud.version>2022.0.0</spring-cloud.version>		
		<!--spring-cloud.version>2021.0.5</spring-cloud.version-->
	</properties>
	<dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-kafka</artifactId>
        </dependency>	
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency> 		
	</dependencies>
	<build>
        <finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
```
if you downgrade to spring boot 2.7.5 and cloud 2021.0.5 then the tombstone message works as expected

**Comment by Virendra045** [comment]
i am facing issue with my code. how to fix this?

**Comment by ivangfr** [comment]
I am facing the same issue in this project https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers when using `Avro`. I am using spring-boot `3.0.2` and spring-cloud `2002.0.1`

**Comment by janson653** [comment]
any update?

**Comment by dann41** [comment]
I am facing the same problem in a Kotlin project with latest version of Spring Cloud Stream. 

Converting KafkaNull to null makes the consumer invocation to fail with a null pointer.

<img width="990" alt="image" src="https://github.com/spring-cloud/spring-cloud-stream/assets/728579/a8535986-858d-4eaa-b45b-4c4b5f48beeb">

In previous versions, the consumer receives a message with the headers that I use to identify the message key. With the latest version this is no longer possible as the whole message is converted to null (not the payload).

What's the reason for the null conversion?

**Comment by cooldroid** [comment]
With this change in place, how do we handle deletion use-case where you need to delete a record on the database based on the key of the Message?

**Comment by sobychacko** [comment]
We introduced a regression with this commit. It is now addressed. See this issue for more details: https://github.com/spring-cloud/spring-cloud-function/issues/1060.

**Comment by balakware** [comment]
@sobychacko how can we update to latest version , do not see 4.1.0 in maven central and neither does the 4.0.4 version has any updates after July 27th, can you help here and point me to the artifact for 4.0.x version where it is fixed

**Comment by sobychacko** [comment]
`4.1.0` is not GA yet. The `RC1` is in the week of 10/23. GA is next month. I'm not sure when we will do the next GA for `4.0.x` yet.

**Comment by VijithPeedikaKandiyil** [comment]
I am using spring-cloud-function-context 4.0.5 but getting same error

**Comment by sobychacko** [comment]
@akibandali This is released as part of Spring Cloud Stream `4.1.0` which is available via spring cloud [2023.0.0](https://spring.io/blog/2023/12/06/spring-cloud-2023-0-0-aka-leyton-is-now-available/).

**Comment by akibandali** [comment]
Thanks, @sobychacko, can you confirm if it is fixed in 4.0.x?

**Comment by sobychacko** [comment]
`4.0.x` versions of both Spring Cloud Stream (`4.0.5`) and Spring Cloud Function (`4.0.6`), where the regression is addressed, are going to be part of Spring Cloud `2022.0.5`, which is getting released [this week], (https://calendar.spring.io/). Please watch the announcements on spring.io for updates on the release.

**Comment by sambhav8695** [comment]
@sobychacko I tried with the version 4.1.0 and 4.0.5 and still facing the issue, can you please help with the version where this is fixed?

**Comment by sobychacko** [comment]
@sambhav8695 Could you tell me what is not working? The original issue or the regression that was introduced from the fix. The changes are part of both of those versions. If you give us more details or a sample app where we can quickly reproduce the issue, we would be happy to take a look further. Also, this is a closed issue. Rather than commenting on this one, I suggest creating a new issue and then linking this one to the new one.
