### ISSUE TITLE
Converting Kotlin Consumer to the java.util.Function

### ISSUE THREAD

**Issue by ggreen** [spring-cloud/spring-cloud-stream#2704]
I have a Koltin Consumer as a sink
```
@Component
public open class GemFireSink(
    val region: Region<Any, PdxInstance>,
    val pdx: PDX,
    @Value("\${keyFieldExpression:id}") val keyFieldExpression: String,
    @Value("\${valuePdxClassName:java.lang.Object}") val valuePdxClassName: String)
    : Consumer<String>
{
    override fun accept(json: String) {
           println(json);
        val formattedType = pdx.addTypeToJson(json,valuePdxClassName);
        var pdxInstance = pdx.fromJSON(formattedType);
        var key = pdxInstance.getField(keyFieldExpression);
        region[key] = pdxInstance;
    }
}
```
I am seeing the following error when receiving messages.
Any suggestion?
```
2023-04-11T14:21:05.396-04:00  INFO 85758 --- [           main] c.v.d.s.spring.gemfire.GemFireSinkAppKt  : Started GemFireSinkAppKt in 27.653 seconds (process running for 29.864)
2023-04-11T14:24:11.033-04:00 ERROR 85758 --- [pool-9-thread-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@7000f658], failedMessage=GenericMessage [payload=byte[20], headers={ContentType=application/json, rabbitmq_streamContext=com.rabbitmq.stream.impl.ConsumersCoordinator$MessageHandlerContext@190a4fb6, deliveryAttempt=3, id=7b70f3fc-ecae-8259-0cf8-e86038061904, sourceData=(Body:'[B@2533afaf(byte[20])' MessageProperties [headers={ContentType=application/json}, contentType=application/octet-stream, contentLength=0, deliveryMode=PERSISTENT, priority=0, deliveryTag=0]), contentType=application/octet-stream, timestamp=1681237447886}]
        at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:191)
        at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:108)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:73)
        at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
        at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
        at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:373)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:327)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:297)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
        at org.springframework.integration.endpoint.MessageProducerSupport.lambda$sendMessage$1(MessageProducerSupport.java:262)
        at io.micrometer.observation.Observation.observe(Observation.java:492)
        at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:262)
        at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$400(AmqpInboundChannelAdapter.java:69)
        at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.lambda$onMessage$0(AmqpInboundChannelAdapter.java:374)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:225)
        at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:370)
        at org.springframework.rabbit.stream.listener.StreamListenerContainer.lambda$setupMessageListener$3(StreamListenerContainer.java:273)
        at com.rabbitmq.stream.impl.StreamConsumer.lambda$new$0(StreamConsumer.java:112)
        at com.rabbitmq.stream.impl.StreamConsumer.lambda$new$7(StreamConsumer.java:240)
        at com.rabbitmq.stream.impl.ConsumersCoordinator$ClientSubscriptionsManager.lambda$new$3(ConsumersCoordinator.java:572)
        at com.rabbitmq.stream.impl.ServerFrameHandler$DeliverVersion1FrameHandler.handleMessage(ServerFrameHandler.java:348)
        at com.rabbitmq.stream.impl.ServerFrameHandler$DeliverVersion1FrameHandler.handleDeliver(ServerFrameHandler.java:475)
        at com.rabbitmq.stream.impl.ServerFrameHandler$DeliverVersion2FrameHandler.doHandle(ServerFrameHandler.java:596)
        at com.rabbitmq.stream.impl.ServerFrameHandler$BaseFrameHandler.handle(ServerFrameHandler.java:262)
        at com.rabbitmq.stream.impl.Client$StreamHandler.lambda$channelRead$1(Client.java:2526)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: class com.vmware.data.solutions.spring.gemfire.GemFireSink cannot be cast to class java.util.function.Function (com.vmware.data.solutions.spring.gemfire.GemFireSink is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @4e50df2e; java.util.function.Function is in module java.base of loader 'bootstrap')
        at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.invoke(KotlinLambdaToFunctionAutoConfiguration.java:126)
        at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.apply(KotlinLambdaToFunctionAutoConfiguration.java:99)
        at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.accept(KotlinLambdaToFunctionAutoConfiguration.java:146)
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeConsumer(SimpleFunctionRegistry.java:990)
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:701)
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:550)
        at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:88)
        at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:785)
        at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:621)
        at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
        ... 34 more
```
Build
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'org.springframework.boot' version '3.0.5'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'org.jetbrains.kotlin.jvm' version '1.7.22'
    id 'org.jetbrains.kotlin.plugin.spring' version '1.7.22'
}


ext {
    set('springCloudVersion', "2022.0.2")
    set('wavefrontVersion', "2.3.4")
    gemFireVersion = '9.15.4'
}

dependencies {
//    implementation "com.vmware.gemfire:spring-data-2.7-gemfire-9.15:1.1.0"
    implementation 'io.pivotal.services.dataTx:gemfire-extensions-core:1.2.0'


    implementation group: 'com.vmware.gemfire', name: 'geode-core', version: gemFireVersion
    implementation group: 'com.vmware.gemfire', name: 'geode-common', version: gemFireVersion
    implementation group: 'com.vmware.gemfire', name: 'geode-lucene', version: gemFireVersion
    implementation group: 'com.vmware.gemfire', name: 'geode-cq', version: gemFireVersion
    implementation group: 'com.vmware.gemfire', name: 'geode-wan', version: gemFireVersion

    implementation project(':components:gemfire-extensions-core')


//    implementation "com.vmware.gemfire:geode-core:9.15.4"
//    implementation "com.vmware.gemfire:geode-cq:9.15.4"

    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    implementation 'org.springframework.cloud:spring-cloud-stream'
    implementation 'org.springframework.cloud:spring-cloud-stream-binder-rabbit'
    implementation 'org.springframework.amqp:spring-rabbit-stream'
    implementation 'com.rabbitmq:stream-client:0.9.0'

//    runtimeOnly 'com.wavefront:wavefront-spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.amqp:spring-rabbit-test'
}
...
...
```

[2:31](https://vmware.slack.com/archives/C06PZDJDV/p1681237873576129)
Looks like it is trying to convert the consumer to the Function
GemFireSink cannot be cast to class java.util.function.Function

**Comment by GrantFleming** [comment]
I have (what I believe) to be the same issue using spring cloud 2021.0.6 (ultimately spring-cloud-function-context 3.2.9 although I can reproduce the issue in spring-cloud-function-context 3.2.10 too).

@Component of type Consumer<X> as my handler and I get the same:

`Caused by: java.lang.ClassCastException: class com.vmware.data.solutions.spring.gemfire.GemFireSink cannot be cast to class java.util.function.Function (com.vmware.data.solutions.spring.gemfire.GemFireSink is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @4e50df2e; java.util.function.Function is in module java.base of loader 'bootstrap')
        at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.invoke(KotlinLambdaToFunctionAutoConfiguration.java:126)`
        
Given where the error eminates from - it might be worth raising this issue against spring-cloud-function rather than here in spring-cloud stream.

**Comment by pcavezzan** [comment]
It seems like starting with spring cloud stream 2021.0.4, you should only define producer, consumer or function as function bean and not anymore as classes (it worked correctly before in 2021.0.3).

As a workaround, what you can do is just define the consumer as bean and then define the bean function which delegate to you consumer bean.
For example:
```Kotlin
@Bean
fun gemFireSink = GemFireSink()

@Bean 
fun gemFireSinkConsumer(gemFireSink: GemFireSink) = Consumer { messages -> gemFireSink.accept(message) }
```

For me, this workaround works like a charm.

**Comment by olegz** [comment]
Actually, can you please upgrade to  2022... There was some work done on SCF and Stream related to that.

**Comment by olegz** [comment]
Closing as the issue has been addressed as part of the other fixes

**Comment by kubav182** [comment]
@olegz using 2023.0.1 still not working getting same error when defining Consumer as class with Component annotation, it works in Java but not in Kotlin

**Comment by junho3** [comment]
Hello. i have same problem in `spring-cloud: 2023.0.1`, `spring-cloud-function-context: 4.1.1`

```
@Component
class TestConsumer : Consumer<String> {
    override fun accept(message: String) {
        println(message)
    }
}
```

using with `Consumer` and `@Component` occurs error.
`Caused by: java.lang.ClassCastException: class com.demo.TestConsumer cannot be cast to class java.util.function.Function
`
```
@Component
class TestConsumer : Function<String, Unit> {
    override fun apply(message: String) {
        println(message)
    }
}
```
but, using with `Function` and `@Component`, it is ok.

what's the difference between Consumer and Function as using funciton style?
@olegz could you please recheck it?

**Comment by olegz** [comment]
Can you please test it with the current snapshot (4.1.2-SNAPSHOT) and report back? I believe it was fixed. You'd have to update both spring-cloud-function-context function and stream

**Comment by junho3** [comment]
@olegz I try to update spring-cloud-function and stream version like this.
```
// as-is
implementation("org.springframework.cloud:spring-cloud-function-kotlin")
implementation("org.springframework.cloud:spring-cloud-stream-binder-kafka")

// to-be
implementation("org.springframework.cloud:spring-cloud-stream:4.1.2-SNAPSHOT")
implementation("org.springframework.cloud:spring-cloud-function-core:4.1.2-SNAPSHOT")
implementation("org.springframework.cloud:spring-cloud-function-context:4.1.2-SNAPSHOT")
implementation("org.springframework.cloud:spring-cloud-function-kotlin:4.1.2-SNAPSHOT")
implementation("org.springframework.cloud:spring-cloud-stream-binder-kafka-core:4.1.2-SNAPSHOT")
implementation("org.springframework.cloud:spring-cloud-stream-binder-kafka:4.1.2-SNAPSHOT")
```

but, it still occurs same error in `Consumer with @Component`.
`Caused by: java.lang.ClassCastException: class com.demo.TestConsumer cannot be cast to class java.util.function.Function 
`

It's the first time I've used the snapshot version, so I might have done something wrong.
If you tell me another way, I'll try.

**Comment by junho3** [comment]
@olegz 
https://github.com/junho3/spring-cloud-stream-binder-kafka-sample here is sample project.
Please check.

**Comment by olegz** [comment]
@junho3 Thank you for example. Yes indeed it was failing, but after upgrading to the latest snapshot it is working fine, so
Update your repo to 
```
maven {
        url = uri("https://repo.spring.io/snapshot")
    }
```
and change spring-cloud version to 

```
extra["springCloudVersion"] = "2023.0.2-SNAPSHOT"
```
We are doing the release today, so 2023.0.2 will be available shortly

**Comment by olegz** [comment]
Release has been completed so you can updated to 2023.0.2. 
Closing this

**Comment by junho3** [comment]
@olegz 
thank you for answer.
i try to change spring-cloud 2023.0.2 version and check changed libraries.
```
Gradle: org.springframework.cloud:spring-cloud-function-context:4.1.2
Gradle: org.springframework.cloud:spring-cloud-function-core:4.1.2
Gradle: org.springframework.cloud:spring-cloud-function-kotlin:4.1.2
Gradle: org.springframework.cloud:spring-cloud-function-web:4.1.2
Gradle: org.springframework.cloud:spring-cloud-stream:4.1.2
Gradle: org.springframework.cloud:spring-cloud-stream-binder-kafka:4.1.2
Gradle: org.springframework.cloud:spring-cloud-stream-binder-kafka-core:4.1.2
```

but `Consumer with @Component` still doesn't work. same exception.
```
Caused by: java.lang.ClassCastException: class com.example.demo.SampleConsumer cannot be cast to class java.util.function.Function (com.example.demo.SampleConsumer is in unnamed module of loader 'app'; java.util.function.Function is in module java.base of loader 'bootstrap')
	at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.invoke(KotlinLambdaToFunctionAutoConfiguration.java:126) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.apply(KotlinLambdaToFunctionAutoConfiguration.java:99) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.accept(KotlinLambdaToFunctionAutoConfiguration.java:146) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeConsumer(SimpleFunctionRegistry.java:1055) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:753) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:592) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:92) ~[spring-cloud-stream-4.1.2.jar:4.1.2]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:823) ~[spring-cloud-stream-4.1.2.jar:4.1.2]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:654) ~[spring-cloud-stream-4.1.2.jar:4.1.2]
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105) ~[spring-integration-core-6.3.0.jar:6.3.0]
	... 36 common frames omitted
```
you can check sample project.

in my test, it works well in java. but just problem in kotlin.
is there anything I missed?

**Comment by olegz** [comment]
Not sure what happened, but i could swear I had it passing.
In any event, i can see the problem is still there. Fixing

**Comment by olegz** [comment]
It is fixed with https://github.com/spring-cloud/spring-cloud-function/commit/05416dbc30ecab8a2bda237923ef205c9a3bda06, so please update spring-cloud-function-context to 4.1.3-SNAPSHOT or spring-cloud to 2023.0.3-SNAPSHOT

**Comment by junho3** [comment]
@olegz I see that there are no issues with spring-cloud-stream 2023.0.3-SNAPSHOT.
Thank you for your help. 👍
